# Generated by Django 2.0.6 on 2018-06-18 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='assets/user/aa.jpg', upload_to='user/'),
        ),
    ]
