# Generated by Django 2.0.6 on 2018-06-21 07:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('word', '0001_initial'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('isChecked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Recitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DurationField(default=datetime.timedelta(1))),
                ('lastRecitedTime', models.DateField(auto_now=True)),
                ('recitedTimeCount', models.IntegerField(default=0)),
                ('successTimeCount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('targetNumber', models.IntegerField(default=20)),
                ('wordbook', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='word.WordBook')),
            ],
        ),
        migrations.AddField(
            model_name='recitation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recitation',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='word.Word'),
        ),
        migrations.AddField(
            model_name='plan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plan',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='word.Word'),
        ),
        migrations.AlterUniqueTogether(
            name='recitation',
            unique_together={('user', 'word')},
        ),
    ]
