# Generated by Django 2.0.6 on 2018-06-18 03:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recitation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DurationField(default=datetime.timedelta(1))),
                ('lastRecitedTime', models.DateTimeField(auto_now=True)),
                ('recitedTimeCount', models.IntegerField(default=0)),
                ('successTimeCount', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='word.Word')),
            ],
        ),
        migrations.AddField(
            model_name='subscription',
            name='targetNumber',
            field=models.IntegerField(default=20),
        ),
    ]
