# Generated by Django 2.0.6 on 2018-06-21 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recitation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='times',
            field=models.IntegerField(default=0),
        ),
    ]
