# Generated by Django 2.0.6 on 2018-06-21 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordbook',
            name='type',
            field=models.CharField(choices=[('zk', '中考'), ('gk', '高考'), ('ky', '考研'), ('cet4', '四级'), ('cet6', '六级'), ('ielts', '雅思'), ('toefl', '托福'), ('gre', 'GRE')], max_length=4, unique=True),
        ),
    ]
