# Generated by Django 2.0.6 on 2018-06-18 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pronunciation',
            name='audio',
            field=models.FileField(upload_to='word'),
        ),
        migrations.AlterField(
            model_name='wordbook',
            name='cover',
            field=models.ImageField(default='user/aa.jpg', upload_to='wordbook'),
        ),
    ]
