# Generated by Django 2.0.6 on 2018-06-21 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0002_auto_20180621_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='wordbook',
        ),
        migrations.AddField(
            model_name='word',
            name='wordbook',
            field=models.ManyToManyField(to='word.WordBook'),
        ),
    ]
