# Generated by Django 2.0.6 on 2018-06-21 16:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('word', '0004_auto_20180621_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='tag',
            field=models.CharField(default='ud', max_length=50),
        ),
        migrations.AlterField(
            model_name='wordbook',
            name='introduction',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='wordbook',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='wordbook',
            name='type',
            field=models.CharField(choices=[('zk', '中考'), ('gk', '高考'), ('ky', '考研'), ('cet4', '四级'), ('cet6', '六级'), ('ielts', '雅思'), ('toefl', '托福'), ('gre', 'GRE'), ('ud', 'User Defined')], max_length=4),
        ),
        migrations.AlterUniqueTogether(
            name='wordbook',
            unique_together={('type', 'creator')},
        ),
    ]
