# Generated by Django 2.0.6 on 2018-06-23 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0005_auto_20180622_0006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='definitation',
            new_name='definition',
        ),
    ]
