# Generated by Django 2.0.6 on 2018-06-24 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0006_auto_20180623_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordbook',
            name='cover',
            field=models.ImageField(default='wordbook/default.jpg', upload_to='wordbook/'),
        ),
    ]
